# This file is part of the Promptly.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: Build & Test

on:
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - 'dependabot/**'

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 12 * * *'
      #      | | | | |
      #      | | | | |____ day of the week (0 - 6 or SUN-SAT)
      #      | | | |____ month (1 - 12 or JAN-DEC)
      #      | | |____ day of the month (1 - 31)
      #      | |____ hour (0 - 23)
      #      |____ minute (0 - 59)

jobs:
  tests:
    name: Frontend
    runs-on: ${{ matrix.os }}

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        node:
          - '16'
        os:
          - ubuntu-latest

    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: 'Setup Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json


      - name: 'Setup npm cache on ${{ runner.os }}'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: package.json self-test
        run: npm run intro
        working-directory: frontend

      - name: Install JS dependencies
        run: npm ci
        working-directory: frontend

      - name: Build JS bundle
        run: npm run build
        working-directory: frontend

      - name: Run JS unit tests with coverage
        run: npm run test
        working-directory: frontend

      - uses: codecov/codecov-action@v3.1.4
        if: success()
        with:
          fail_ci_if_error: true
          verbose: true
          name: codecov-umbrella
          flags: unittests,frontend
          env_vars: OS,NODE_VERSION
